// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentJob = __t.object("AgentJob", {
  createdAt: __t.timestamp(),
  error: __t.option(__t.string()),
  finalResult: __t.option(__t.string()),
  jobId: __t.string(),
  prompt: __t.string(),
  requestedAgent: __t.option(__t.string()),
  selectedAgents: __t.option(__t.string()),
  status: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AgentJob = __Infer<typeof AgentJob>;

export const AgentStep = __t.object("AgentStep", {
  agent: __t.string(),
  createdAt: __t.timestamp(),
  input: __t.string(),
  jobId: __t.string(),
  output: __t.option(__t.string()),
  status: __t.string(),
  stepId: __t.string(),
  stepOrder: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type AgentStep = __Infer<typeof AgentStep>;

export const Person = __t.object("Person", {
  id: __t.u64(),
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

