// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  workspaceId: __t.u64().name("workspace_id"),
  name: __t.string(),
  topic: __t.string(),
  canvasX: __t.i32().name("canvas_x"),
  canvasY: __t.i32().name("canvas_y"),
  memoryBackend: __t.string().name("memory_backend"),
  memoryNamespace: __t.string().name("memory_namespace"),
  status: __t.u8(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
});
