// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  createdAt: __t.timestamp().name("created_at"),
  error: __t.option(__t.string()),
  finalResult: __t.option(__t.string()).name("final_result"),
  jobId: __t.string().primaryKey().name("job_id"),
  prompt: __t.string(),
  requestedAgent: __t.option(__t.string()).name("requested_agent"),
  selectedAgents: __t.option(__t.string()).name("selected_agents"),
  status: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
