// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  agentId: __t.u64().primaryKey().name("agent_id"),
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.identity().name("created_by"),
  modelName: __t.string().name("model_name"),
  modelProvider: __t.string().name("model_provider"),
  name: __t.string(),
  systemPrompt: __t.string().name("system_prompt"),
  tools: __t.array(__t.string()),
  workspaceId: __t.u64().name("workspace_id"),
});
