// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  jobId: __t.u64().primaryKey().name("job_id"),
  threadId: __t.u64().name("thread_id"),
  roomId: __t.u64().name("room_id"),
  prompt: __t.string(),
  taggedAgent: __t.option(__t.u64()).name("tagged_agent"),
  angle: __t.string(),
  status: __t.u8(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
});
