// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  author: __t.identity(),
  authorAgent: __t.option(__t.u64()).name("author_agent"),
  body: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  mentions: __t.array(__t.u64()),
  messageId: __t.u64().primaryKey().name("message_id"),
  role: __t.u8(),
  roomId: __t.u64().name("room_id"),
  streaming: __t.bool(),
  threadId: __t.u64().name("thread_id"),
});
