// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  memoryId: __t.u64().primaryKey().name("memory_id"),
  roomId: __t.u64().name("room_id"),
  threadId: __t.u64().name("thread_id"),
  summary: __t.string(),
  embeddingRef: __t.option(__t.string()).name("embedding_ref"),
  weight: __t.f32(),
  createdAt: __t.timestamp().name("created_at"),
});
