// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ImageUpload,
} from "./types";

export default {
  angle: __t.string(),
  get images() {
    return __t.array(ImageUpload);
  },
  model: __t.option(__t.string()),
  prompt: __t.string(),
  roomId: __t.u64(),
  taggedAgent: __t.option(__t.u64()),
  title: __t.string(),
};
