// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  threadId: __t.u64().primaryKey().name("thread_id"),
  roomId: __t.u64().name("room_id"),
  title: __t.string(),
  createdBy: __t.identity().name("created_by"),
  status: __t.u8(),
  mergeSessionId: __t.option(__t.u64()).name("merge_session_id"),
  createdAt: __t.timestamp().name("created_at"),
});
