// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  callId: __t.u64().primaryKey().name("call_id"),
  createdAt: __t.timestamp().name("created_at"),
  input: __t.string(),
  jobId: __t.u64().name("job_id"),
  output: __t.option(__t.string()),
  status: __t.u8(),
  tool: __t.string(),
});
