// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveRooms = __t.object("ActiveRooms", {});
export type ActiveRooms = __Infer<typeof ActiveRooms>;

export const Agent = __t.object("Agent", {
  agentId: __t.u64(),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
  modelName: __t.string(),
  modelProvider: __t.string(),
  name: __t.string(),
  systemPrompt: __t.string(),
  tools: __t.array(__t.string()),
  workspaceId: __t.u64(),
});
export type Agent = __Infer<typeof Agent>;

export const AgentJob = __t.object("AgentJob", {
  createdAt: __t.timestamp(),
  error: __t.option(__t.string()),
  finalResult: __t.option(__t.string()),
  jobId: __t.string(),
  prompt: __t.string(),
  requestedAgent: __t.option(__t.string()),
  roomId: __t.option(__t.u64()),
  selectedAgents: __t.option(__t.string()),
  status: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AgentJob = __Infer<typeof AgentJob>;

export const AgentStep = __t.object("AgentStep", {
  agent: __t.string(),
  createdAt: __t.timestamp(),
  input: __t.string(),
  jobId: __t.string(),
  output: __t.option(__t.string()),
  status: __t.string(),
  stepId: __t.string(),
  stepOrder: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type AgentStep = __Infer<typeof AgentStep>;

export const AiJob = __t.object("AiJob", {
  angle: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
  jobId: __t.u64(),
  model: __t.option(__t.string()),
  prompt: __t.string(),
  roomId: __t.u64(),
  status: __t.u8(),
  taggedAgent: __t.option(__t.u64()),
  threadId: __t.u64(),
});
export type AiJob = __Infer<typeof AiJob>;

export const AppUser = __t.object("AppUser", {
  createdAt: __t.timestamp(),
  displayName: __t.string(),
  identity: __t.identity(),
});
export type AppUser = __Infer<typeof AppUser>;

export const Exploration = __t.object("Exploration", {
  angle: __t.string(),
  explorationId: __t.u64(),
  jobId: __t.u64(),
  messageId: __t.u64(),
  sessionId: __t.u64(),
  status: __t.u8(),
});
export type Exploration = __Infer<typeof Exploration>;

export const MergeLink = __t.object("MergeLink", {
  sessionId: __t.u64(),
  threadId: __t.u64(),
});
export type MergeLink = __Infer<typeof MergeLink>;

export const MergeSession = __t.object("MergeSession", {
  createdAt: __t.timestamp(),
  finalMessageId: __t.option(__t.u64()),
  roomId: __t.u64(),
  sessionId: __t.u64(),
  status: __t.u8(),
});
export type MergeSession = __Infer<typeof MergeSession>;

export const Message = __t.object("Message", {
  author: __t.identity(),
  authorAgent: __t.option(__t.u64()),
  body: __t.string(),
  createdAt: __t.timestamp(),
  mentions: __t.array(__t.u64()),
  messageId: __t.u64(),
  role: __t.u8(),
  roomId: __t.u64(),
  streaming: __t.bool(),
  threadId: __t.u64(),
});
export type Message = __Infer<typeof Message>;

export const MessageChunk = __t.object("MessageChunk", {
  chunkId: __t.u64(),
  createdAt: __t.timestamp(),
  delta: __t.string(),
  idx: __t.u32(),
  messageId: __t.u64(),
});
export type MessageChunk = __Infer<typeof MessageChunk>;

export const Room = __t.object("Room", {
  canvasX: __t.i32(),
  canvasY: __t.i32(),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
  memoryBackend: __t.string(),
  memoryNamespace: __t.string(),
  name: __t.string(),
  roomId: __t.u64(),
  status: __t.u8(),
  topic: __t.string(),
  workspaceId: __t.u64(),
});
export type Room = __Infer<typeof Room>;

export const RoomAgent = __t.object("RoomAgent", {
  addedAt: __t.timestamp(),
  agentId: __t.u64(),
  roomId: __t.u64(),
});
export type RoomAgent = __Infer<typeof RoomAgent>;

export const RoomHuman = __t.object("RoomHuman", {
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
  roomId: __t.u64(),
});
export type RoomHuman = __Infer<typeof RoomHuman>;

export const RoomMemoryEntry = __t.object("RoomMemoryEntry", {
  createdAt: __t.timestamp(),
  embeddingRef: __t.option(__t.string()),
  memoryId: __t.u64(),
  roomId: __t.u64(),
  summary: __t.string(),
  threadId: __t.u64(),
  weight: __t.f32(),
});
export type RoomMemoryEntry = __Infer<typeof RoomMemoryEntry>;

export const RoomPresence = __t.object("RoomPresence", {
  identity: __t.identity(),
  lastSeen: __t.timestamp(),
  roomId: __t.u64(),
});
export type RoomPresence = __Infer<typeof RoomPresence>;

export const SnapshotTimer = __t.object("SnapshotTimer", {
  scheduledAt: __t.scheduleAt(),
  scheduledId: __t.u64(),
  workspaceId: __t.u64(),
});
export type SnapshotTimer = __Infer<typeof SnapshotTimer>;

export const StreamEvent = __t.object("StreamEvent", {
  createdAt: __t.timestamp(),
  kind: __t.string(),
  messageId: __t.u64(),
  payload: __t.string(),
});
export type StreamEvent = __Infer<typeof StreamEvent>;

export const Thread = __t.object("Thread", {
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
  mergeSessionId: __t.option(__t.u64()),
  roomId: __t.u64(),
  status: __t.u8(),
  threadId: __t.u64(),
  title: __t.string(),
});
export type Thread = __Infer<typeof Thread>;

export const ToolCall = __t.object("ToolCall", {
  callId: __t.u64(),
  createdAt: __t.timestamp(),
  input: __t.string(),
  jobId: __t.u64(),
  output: __t.option(__t.string()),
  status: __t.u8(),
  tool: __t.string(),
});
export type ToolCall = __Infer<typeof ToolCall>;

export const WorkerAllowlist = __t.object("WorkerAllowlist", {
  addedAt: __t.timestamp(),
  identity: __t.identity(),
  label: __t.string(),
});
export type WorkerAllowlist = __Infer<typeof WorkerAllowlist>;

export const Workspace = __t.object("Workspace", {
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
  name: __t.string(),
  workspaceId: __t.u64(),
});
export type Workspace = __Infer<typeof Workspace>;

export const WorkspaceSnapshot = __t.object("WorkspaceSnapshot", {
  generatedAt: __t.timestamp(),
  payload: __t.string(),
  snapshotId: __t.u64(),
  workspaceId: __t.u64(),
});
export type WorkspaceSnapshot = __Infer<typeof WorkspaceSnapshot>;

