// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  generatedAt: __t.timestamp().name("generated_at"),
  payload: __t.string(),
  snapshotId: __t.u64().primaryKey().name("snapshot_id"),
  workspaceId: __t.u64().name("workspace_id"),
});
