// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddStepReducer from "../add_step_reducer";
import AddAgentToRoomReducer from "../add_agent_to_room_reducer";
import AppendChunkReducer from "../append_chunk_reducer";
import ArchiveRoomReducer from "../archive_room_reducer";
import ClaimJobReducer from "../claim_job_reducer";
import CloseThreadReducer from "../close_thread_reducer";
import CompleteJobReducer from "../complete_job_reducer";
import CreateJobReducer from "../create_job_reducer";
import CreateRoomReducer from "../create_room_reducer";
import CreateWorkspaceReducer from "../create_workspace_reducer";
import FailJobReducer from "../fail_job_reducer";
import GenerateSnapshotReducer from "../generate_snapshot_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import LinkThreadToMergeReducer from "../link_thread_to_merge_reducer";
import LogToolCallReducer from "../log_tool_call_reducer";
import MarkExplorationReducer from "../mark_exploration_reducer";
import MoveRoomReducer from "../move_room_reducer";
import OpenMergeSessionReducer from "../open_merge_session_reducer";
import PostMessageReducer from "../post_message_reducer";
import PublishSynthesisReducer from "../publish_synthesis_reducer";
import PushRoomMemoryReducer from "../push_room_memory_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import RegisterWorkerReducer from "../register_worker_reducer";
import RemoveAgentFromRoomReducer from "../remove_agent_from_room_reducer";
import ResolveToolCallReducer from "../resolve_tool_call_reducer";
import SignalEventReducer from "../signal_event_reducer";
import StartThreadReducer from "../start_thread_reducer";
import UpdateJobReducer from "../update_job_reducer";
import UpdateStepReducer from "../update_step_reducer";
import UpdateAgentReducer from "../update_agent_reducer";
import UpdateDisplayNameReducer from "../update_display_name_reducer";
import UpdateExplorationReducer from "../update_exploration_reducer";

export type AddStepParams = __Infer<typeof AddStepReducer>;
export type AddAgentToRoomParams = __Infer<typeof AddAgentToRoomReducer>;
export type AppendChunkParams = __Infer<typeof AppendChunkReducer>;
export type ArchiveRoomParams = __Infer<typeof ArchiveRoomReducer>;
export type ClaimJobParams = __Infer<typeof ClaimJobReducer>;
export type CloseThreadParams = __Infer<typeof CloseThreadReducer>;
export type CompleteJobParams = __Infer<typeof CompleteJobReducer>;
export type CreateJobParams = __Infer<typeof CreateJobReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type CreateWorkspaceParams = __Infer<typeof CreateWorkspaceReducer>;
export type FailJobParams = __Infer<typeof FailJobReducer>;
export type GenerateSnapshotParams = __Infer<typeof GenerateSnapshotReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type LinkThreadToMergeParams = __Infer<typeof LinkThreadToMergeReducer>;
export type LogToolCallParams = __Infer<typeof LogToolCallReducer>;
export type MarkExplorationParams = __Infer<typeof MarkExplorationReducer>;
export type MoveRoomParams = __Infer<typeof MoveRoomReducer>;
export type OpenMergeSessionParams = __Infer<typeof OpenMergeSessionReducer>;
export type PostMessageParams = __Infer<typeof PostMessageReducer>;
export type PublishSynthesisParams = __Infer<typeof PublishSynthesisReducer>;
export type PushRoomMemoryParams = __Infer<typeof PushRoomMemoryReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type RegisterWorkerParams = __Infer<typeof RegisterWorkerReducer>;
export type RemoveAgentFromRoomParams = __Infer<typeof RemoveAgentFromRoomReducer>;
export type ResolveToolCallParams = __Infer<typeof ResolveToolCallReducer>;
export type SignalEventParams = __Infer<typeof SignalEventReducer>;
export type StartThreadParams = __Infer<typeof StartThreadReducer>;
export type UpdateJobParams = __Infer<typeof UpdateJobReducer>;
export type UpdateStepParams = __Infer<typeof UpdateStepReducer>;
export type UpdateAgentParams = __Infer<typeof UpdateAgentReducer>;
export type UpdateDisplayNameParams = __Infer<typeof UpdateDisplayNameReducer>;
export type UpdateExplorationParams = __Infer<typeof UpdateExplorationReducer>;

